### ISSUE TITLE
Vte.Terminal.fork_command_full removed

### ISSUE THREAD

**Issue by ishankhare07** [lazka/pgi-docs#1]
this has popped up recently (probably in the last week)
python3, ubuntu 15.04 shows the following error:

``` python
AttributeError: 'Terminal' object has no attribute 'fork_command_full'
```

I noticed that this function seems to be removed from the docs, how can i now use the required functionality, any new function it got replaced with?

**Comment by lazka** [comment]
Vte had an API version bump some time ago (2.91), and I guess removed that function. The docs only contain the newer version atm because I use debian and the packages containing the gir aren't parallel installable (not sure how to fix that..)

The following should fix the program error:

```
import gi
gi.require_version("Vte", "2.90")
from gi.repository import Vte
```

I don't know anything about Vte, so try to ask the maintainers/developers how to replace fork_command_full

**Comment by ishankhare07** [comment]
i get the following error

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 104, in require_version
    (namespace, version))
ValueError: Namespace Vte not available for version 2.90
```

**Comment by lazka** [comment]
```
sudo apt-get install gir1.2-vte-2.90
```

**Comment by lazka** [comment]
I've filed https://github.com/lazka/pgi-docgen/issues/90

**Comment by ishankhare07** [comment]
thanks, it did work
however what's currently the official way of getting a working Vte.Terminal widget while using the updated library? Vte.Pte?

**Comment by lazka** [comment]
As I said, I don't know anything about Vte.

**Comment by ishankhare07** [comment]
your also own the [pgi](https://github.com/lazka/pgi) repository which i suppose are the python bindings for GTK+, and the main source of this api change is the binding itself. If not "pgi", then where must it be appropriate to open a new issue as [gnome vte](https://github.com/GNOME/vte) is just for the core library and seems it has nothing to do with the python bindings

**Comment by lazka** [comment]
pgi are experimental PyPy bindings. The real ones are PyGObject.

For how the bindings work: Each C library provides a file describing how to wrap the library in other languages (Python/JS/Vala). The Python bindings use that file and automatically create bindings at runtime. All the info in that file gets derived from the C source and the C comments containing special annotations + some runtime introspection.

See "GObject Introspection" for more info on that.

Back to "Vte.Terminal.fork_command_full", I see in the git history that it was renamed to "Vte.Terminal.spawn_sync" and made cancel-able. Maybe that helps.

**Comment by lazka** [comment]
https://lazka.github.io/pgi-docs/#Vte-2.90/classes/Terminal.html#Vte.Terminal.fork_command_full
is back now.

The sidebar search will only search in newer versions (2.91) but the docs of the older version are still accessible manually.
