### ISSUE TITLE
Links broken in rendered README.rst

### ISSUE THREAD

**Issue by cjmayo** [lazka/pgi-docs#2]
The commit:
https://github.com/lazka/pgi-docs/commit/40f76cb217cb37223efc2a65ac8f07ebc5a12fe9#diff-88b99bb28683bd5b7e3a204826ead112

replaced newlines with \n which adds n to the first couple of links.

**Comment by lazka** [comment]
Yeah, I haven't figure out why. For some reason the following script does this since it gets executed on azure: https://github.com/pygobject/pgi-docgen/blob/master/tools/push.sh

**Comment by lazka** [comment]
ah, I was using zsh which has an echo builtin with escapes enabled by default.

**Comment by lazka** [comment]
Fixed. Thanks for the report.
